package pineapple.bd.com.pineapple.db;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import pineapple.bd.com.pineapple.db.User;
import pineapple.bd.com.pineapple.db.UserAuth;

import pineapple.bd.com.pineapple.db.UserDao;
import pineapple.bd.com.pineapple.db.UserAuthDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig userDaoConfig;
    private final DaoConfig userAuthDaoConfig;

    private final UserDao userDao;
    private final UserAuthDao userAuthDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        userDaoConfig = daoConfigMap.get(UserDao.class).clone();
        userDaoConfig.initIdentityScope(type);

        userAuthDaoConfig = daoConfigMap.get(UserAuthDao.class).clone();
        userAuthDaoConfig.initIdentityScope(type);

        userDao = new UserDao(userDaoConfig, this);
        userAuthDao = new UserAuthDao(userAuthDaoConfig, this);

        registerDao(User.class, userDao);
        registerDao(UserAuth.class, userAuthDao);
    }
    
    public void clear() {
        userDaoConfig.getIdentityScope().clear();
        userAuthDaoConfig.getIdentityScope().clear();
    }

    public UserDao getUserDao() {
        return userDao;
    }

    public UserAuthDao getUserAuthDao() {
        return userAuthDao;
    }

}
