package pineapple.bd.com.pineapple.db;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 

import cn.bmob.v3.BmobObject;

/**
 * Entity mapped to table "USER".
 */
public class User extends BmobObject{

    private Long id;
    private String nickname;
    private String avatar;
    private Integer gender;
    private String hobbies;
    private String jobs;

    public User() {
    }

    public User(Long id) {
        this.id = id;
    }

    public User(Long id, String nickname, String avatar, Integer gender, String hobbies, String jobs) {
        this.id = id;
        this.nickname = nickname;
        this.avatar = avatar;
        this.gender = gender;
        this.hobbies = hobbies;
        this.jobs = jobs;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getNickname() {
        return nickname;
    }

    public void setNickname(String nickname) {
        this.nickname = nickname;
    }

    public String getAvatar() {
        return avatar;
    }

    public void setAvatar(String avatar) {
        this.avatar = avatar;
    }

    public Integer getGender() {
        return gender;
    }

    public void setGender(Integer gender) {
        this.gender = gender;
    }

    public String getHobbies() {
        return hobbies;
    }

    public void setHobbies(String hobbies) {
        this.hobbies = hobbies;
    }

    public String getJobs() {
        return jobs;
    }

    public void setJobs(String jobs) {
        this.jobs = jobs;
    }

}
