package pineapple.bd.com.pineapple.db;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "USER_AUTH".
 */
public class UserAuth extends cn.bmob.v3.BmobObject  {

    private Long id;
    private String user_id;
    private Integer identity_type;
    private String identify_unique_id ;
    private String credential;
    private Boolean verified;

    public UserAuth() {
    }

    public UserAuth(Long id) {
        this.id = id;
    }

    public UserAuth(Long id, String user_id, Integer identity_type, String identify_unique_id , String credential, Boolean verified) {
        this.id = id;
        this.user_id = user_id;
        this.identity_type = identity_type;
        this.identify_unique_id  = identify_unique_id ;
        this.credential = credential;
        this.verified = verified;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getUser_id() {
        return user_id;
    }

    public void setUser_id(String user_id) {
        this.user_id = user_id;
    }

    public Integer getIdentity_type() {
        return identity_type;
    }

    public void setIdentity_type(Integer identity_type) {
        this.identity_type = identity_type;
    }

    public String getIdentify_unique_id () {
        return identify_unique_id ;
    }

    public void setIdentify_unique_id (String identify_unique_id ) {
        this.identify_unique_id  = identify_unique_id ;
    }

    public String getCredential() {
        return credential;
    }

    public void setCredential(String credential) {
        this.credential = credential;
    }

    public Boolean getVerified() {
        return verified;
    }

    public void setVerified(Boolean verified) {
        this.verified = verified;
    }

}
